import type { GalleryItem } from './gallery-types'

/**
 * Gallery image base URL — points to Cloudflare R2 bucket.
 * Change this to your R2 custom domain or public bucket URL.
 * Images should be uploaded to: <GALLERY_CDN_BASE>/gallery/<filename>
 */
export const GALLERY_CDN_BASE =
  process.env.NEXT_PUBLIC_GALLERY_CDN_BASE || ''

/** Build full image URL from relative path */
export function galleryImageUrl(path: string): string {
  if (path.startsWith('http')) return path
  return `${GALLERY_CDN_BASE}${path}`
}

/**
 * Built-in gallery items for the scientific figure gallery.
 * imagePath values are relative to GALLERY_CDN_BASE.
 * Set NEXT_PUBLIC_GALLERY_CDN_BASE env var to your R2 domain
 * (e.g. https://gallery.figure.vlooong.top) for production.
 */
export const galleryItems: GalleryItem[] = [
  {
    id: 'g-001',
    title: 'Multi-panel Time Series Comparison',
    titleZh: '多面板时序对比图',
    description: 'Clean line chart comparing multiple algorithms across time series datasets, Nature-style layout with muted color palette.',
    descriptionZh: '清晰的折线图对比多种算法在时序数据集上的表现，Nature 风格布局，配色柔和。',
    imagePath: '/gallery/nature-timeseries.svg',
    thumbnailPath: '/gallery/nature-timeseries.svg',
    source: { type: 'paper', name: 'Nature Methods 2024', url: 'https://doi.org/10.1038/s41592-024' },
    chartTypes: ['line'],
    journalStyles: ['Nature'],
    colorTones: ['muted'],
    colorPalette: ['#4E79A7', '#F28E2B', '#E15759', '#76B7B2', '#59A14F'],
    createdAt: Date.now(),
  },
  {
    id: 'g-002',
    title: 'Grouped Bar Chart with Error Bars',
    titleZh: '分组柱状图（含误差线）',
    description: 'Grouped bar chart comparing model performance metrics with standard deviation error bars, IEEE conference style.',
    descriptionZh: '分组柱状图对比模型性能指标，带标准差误差线，IEEE 会议风格。',
    imagePath: '/gallery/ieee-bar.svg',
    thumbnailPath: '/gallery/ieee-bar.svg',
    source: { type: 'paper', name: 'IEEE TPAMI 2024' },
    chartTypes: ['bar'],
    journalStyles: ['IEEE'],
    colorTones: ['cool'],
    colorPalette: ['#1F77B4', '#FF7F0E', '#2CA02C', '#D62728'],
    createdAt: Date.now(),
  },
  {
    id: 'g-003',
    title: 'Scatter Plot with Density Contours',
    titleZh: '带密度等高线的散点图',
    description: 'Scatter plot with marginal density curves and contour overlays, commonly seen in Science papers.',
    descriptionZh: '带边际密度曲线和等高线叠加的散点图，常见于 Science 论文。',
    imagePath: '/gallery/science-scatter.svg',
    thumbnailPath: '/gallery/science-scatter.svg',
    source: { type: 'paper', name: 'Science 2024' },
    chartTypes: ['scatter'],
    journalStyles: ['Science'],
    colorTones: ['cool'],
    colorPalette: ['#3366CC', '#DC3912', '#FF9900', '#109618'],
    createdAt: Date.now(),
  },
  {
    id: 'g-004',
    title: 'Heatmap with Hierarchical Clustering',
    titleZh: '层次聚类热力图',
    description: 'Gene expression heatmap with dendrogram, using a blue-white-red diverging colormap.',
    descriptionZh: '基因表达热力图配合树状图，使用蓝-白-红双色渐变。',
    imagePath: '/gallery/heatmap-cluster.svg',
    thumbnailPath: '/gallery/heatmap-cluster.svg',
    source: { type: 'paper', name: 'Cell 2024' },
    chartTypes: ['heatmap'],
    journalStyles: ['Cell'],
    colorTones: ['cool'],
    colorPalette: ['#2166AC', '#F7F7F7', '#B2182B'],
    createdAt: Date.now(),
  },
  {
    id: 'g-005',
    title: 'Box Plot with Jitter Points',
    titleZh: '箱线图（含抖动散点）',
    description: 'Box plot showing distribution of measurement values across groups, with individual data points overlaid as jitter.',
    descriptionZh: '箱线图展示各组测量值分布，叠加抖动散点显示单个数据点。',
    imagePath: '/gallery/boxplot-jitter.svg',
    thumbnailPath: '/gallery/boxplot-jitter.svg',
    source: { type: 'paper', name: 'PNAS 2024' },
    chartTypes: ['box'],
    journalStyles: ['PNAS'],
    colorTones: ['vibrant'],
    colorPalette: ['#E64B35', '#4DBBD5', '#00A087', '#3C5488'],
    createdAt: Date.now(),
  },
  {
    id: 'g-006',
    title: 'Violin Plot Comparison',
    titleZh: '小提琴图对比',
    description: 'Split violin plots comparing two conditions, showing full distribution shape with quartile markers.',
    descriptionZh: '分半小提琴图对比两种条件，展示完整分布形态并标记四分位数。',
    imagePath: '/gallery/violin-comparison.svg',
    thumbnailPath: '/gallery/violin-comparison.svg',
    source: { type: 'paper', name: 'Nature Communications 2024' },
    chartTypes: ['violin'],
    journalStyles: ['Nature'],
    colorTones: ['muted'],
    colorPalette: ['#7570B3', '#D95F02', '#1B9E77'],
    createdAt: Date.now(),
  },
  {
    id: 'g-007',
    title: 'Stacked Area Chart',
    titleZh: '堆叠面积图',
    description: 'Proportional stacked area chart showing composition changes over time, ACS journal style.',
    descriptionZh: '比例堆叠面积图展示成分随时间的变化，ACS 期刊风格。',
    imagePath: '/gallery/acs-area.svg',
    thumbnailPath: '/gallery/acs-area.svg',
    source: { type: 'paper', name: 'ACS Nano 2024' },
    chartTypes: ['area'],
    journalStyles: ['ACS'],
    colorTones: ['warm'],
    colorPalette: ['#E41A1C', '#377EB8', '#4DAF4A', '#984EA3', '#FF7F00'],
    createdAt: Date.now(),
  },
  {
    id: 'g-008',
    title: 'Radar Chart for Multi-metric Evaluation',
    titleZh: '多指标雷达图',
    description: 'Radar/spider chart comparing multiple algorithms across different evaluation metrics.',
    descriptionZh: '雷达图对比多种算法在不同评价指标上的表现。',
    imagePath: '/gallery/radar-eval.svg',
    thumbnailPath: '/gallery/radar-eval.svg',
    source: { type: 'website', name: 'Matplotlib Gallery', url: 'https://matplotlib.org/stable/gallery/' },
    chartTypes: ['radar'],
    journalStyles: ['Custom'],
    colorTones: ['vibrant'],
    colorPalette: ['#FF6384', '#36A2EB', '#FFCE56', '#4BC0C0'],
    createdAt: Date.now(),
  },
  {
    id: 'g-009',
    title: 'Publication-ready Dual Y-axis Plot',
    titleZh: '双Y轴出版级图表',
    description: 'Dual Y-axis line chart with different scales, Nature-style formatting with high-contrast colors.',
    descriptionZh: '双Y轴折线图，不同刻度，Nature风格排版，高对比配色。',
    imagePath: '/gallery/dual-yaxis.svg',
    thumbnailPath: '/gallery/dual-yaxis.svg',
    source: { type: 'paper', name: 'Nature Energy 2024' },
    chartTypes: ['line'],
    journalStyles: ['Nature'],
    colorTones: ['neutral'],
    colorPalette: ['#0072B2', '#D55E00', '#009E73', '#CC79A7'],
    createdAt: Date.now(),
  },
  {
    id: 'g-010',
    title: 'Colorful Sankey Flow Diagram',
    titleZh: '彩色桑基图',
    description: 'Sankey diagram showing data flow between categories with vibrant gradient colors.',
    descriptionZh: '桑基图展示类别之间的数据流动，使用鲜艳渐变配色。',
    imagePath: '/gallery/sankey-flow.svg',
    thumbnailPath: '/gallery/sankey-flow.svg',
    source: { type: 'website', name: 'D3.js Gallery', url: 'https://d3js.org/' },
    chartTypes: ['sankey'],
    journalStyles: ['Custom'],
    colorTones: ['vibrant'],
    colorPalette: ['#a6cee3', '#1f78b4', '#b2df8a', '#33a02c', '#fb9a99'],
    createdAt: Date.now(),
  },
  {
    id: 'g-011',
    title: 'Minimalist Line Chart',
    titleZh: '极简折线图',
    description: 'Clean, minimal line chart with a single color and no grid, ideal for presentations.',
    descriptionZh: '干净极简的单色折线图，无网格线，适合演示。',
    imagePath: '/gallery/minimal-line.svg',
    thumbnailPath: '/gallery/minimal-line.svg',
    source: { type: 'website', name: 'Tufte Principles' },
    chartTypes: ['line'],
    journalStyles: ['Custom'],
    colorTones: ['monochrome'],
    colorPalette: ['#333333', '#999999', '#CCCCCC'],
    createdAt: Date.now(),
  },
  {
    id: 'g-012',
    title: 'Warm-toned Bar Chart',
    titleZh: '暖色调柱状图',
    description: 'Horizontal bar chart with warm autumn palette, suitable for social science publications.',
    descriptionZh: '暖色秋季配色的水平柱状图，适合社会科学出版物。',
    imagePath: '/gallery/warm-bar.svg',
    thumbnailPath: '/gallery/warm-bar.svg',
    source: { type: 'paper', name: 'Lancet 2024' },
    chartTypes: ['bar'],
    journalStyles: ['Lancet'],
    colorTones: ['warm'],
    colorPalette: ['#AD002A', '#ED0000', '#00468B', '#42B540', '#0099B4'],
    createdAt: Date.now(),
  },
  {
    id: 'g-013',
    title: 'Multi-dataset Scatter with Trendlines',
    titleZh: '多数据集散点图（含趋势线）',
    description: 'Scatter plot with linear regression trendlines for multiple groups, IEEE style.',
    descriptionZh: '多组散点图配合线性回归趋势线，IEEE风格。',
    imagePath: '/gallery/scatter-trend.svg',
    thumbnailPath: '/gallery/scatter-trend.svg',
    source: { type: 'paper', name: 'IEEE Access 2024' },
    chartTypes: ['scatter'],
    journalStyles: ['IEEE'],
    colorTones: ['cool'],
    colorPalette: ['#0073C2', '#EFC000', '#868686', '#CD534C'],
    createdAt: Date.now(),
  },
  {
    id: 'g-014',
    title: 'Pie Chart with Percentage Labels',
    titleZh: '带百分比标签的饼图',
    description: 'Donut/pie chart showing proportion distribution with clean labeling.',
    descriptionZh: '环形饼图展示比例分布，标注清晰。',
    imagePath: '/gallery/pie-labels.svg',
    thumbnailPath: '/gallery/pie-labels.svg',
    source: { type: 'website', name: 'ECharts Examples', url: 'https://echarts.apache.org/examples/' },
    chartTypes: ['pie'],
    journalStyles: ['Custom'],
    colorTones: ['vibrant'],
    colorPalette: ['#5470C6', '#91CC75', '#FAC858', '#EE6666', '#73C0DE'],
    createdAt: Date.now(),
  },
  {
    id: 'g-015',
    title: 'Confidence Band Line Plot',
    titleZh: '置信区间折线图',
    description: 'Line plot with shaded confidence interval bands, Nature Methods color scheme.',
    descriptionZh: '带阴影置信区间的折线图，Nature Methods 配色方案。',
    imagePath: '/gallery/confidence-band.svg',
    thumbnailPath: '/gallery/confidence-band.svg',
    source: { type: 'paper', name: 'Nature Methods 2024' },
    chartTypes: ['line', 'area'],
    journalStyles: ['Nature'],
    colorTones: ['muted'],
    colorPalette: ['#4E79A7', '#A0CBE8', '#F28E2B', '#FFBE7D'],
    createdAt: Date.now(),
  },
  {
    id: 'g-016',
    title: 'High-contrast Accessibility Chart',
    titleZh: '高对比度无障碍图表',
    description: 'Chart designed for colorblind accessibility using distinct symbols and patterns.',
    descriptionZh: '为色盲无障碍设计的图表，使用不同符号和图案。',
    imagePath: '/gallery/accessible-chart.svg',
    thumbnailPath: '/gallery/accessible-chart.svg',
    source: { type: 'website', name: 'ColorBrewer', url: 'https://colorbrewer2.org/' },
    chartTypes: ['line'],
    journalStyles: ['Custom'],
    colorTones: ['neutral'],
    colorPalette: ['#000000', '#E69F00', '#56B4E9', '#009E73', '#F0E442'],
    createdAt: Date.now(),
  },
  {
    id: 'g-017',
    title: 'Gradient Heatmap Matrix',
    titleZh: '渐变热力矩阵图',
    description: 'Correlation matrix heatmap using a smooth single-hue gradient from light to dark.',
    descriptionZh: '相关矩阵热力图，使用从浅到深的单色渐变。',
    imagePath: '/gallery/gradient-heatmap.svg',
    thumbnailPath: '/gallery/gradient-heatmap.svg',
    source: { type: 'paper', name: 'Science Advances 2024' },
    chartTypes: ['heatmap'],
    journalStyles: ['Science'],
    colorTones: ['monochrome'],
    colorPalette: ['#F7FBFF', '#6BAED6', '#08306B'],
    createdAt: Date.now(),
  },
  {
    id: 'g-018',
    title: 'Error Bar Comparison Chart',
    titleZh: '误差线对比图',
    description: 'Point chart with error bars for method comparison, clean ACS layout.',
    descriptionZh: '带误差线的点图用于方法对比，简洁 ACS 布局。',
    imagePath: '/gallery/error-bar.svg',
    thumbnailPath: '/gallery/error-bar.svg',
    source: { type: 'paper', name: 'JACS 2024' },
    chartTypes: ['scatter'],
    journalStyles: ['ACS'],
    colorTones: ['cool'],
    colorPalette: ['#1B9E77', '#D95F02', '#7570B3', '#E7298A'],
    createdAt: Date.now(),
  },
  {
    id: 'g-019',
    title: 'Dark Theme Dashboard Chart',
    titleZh: '深色主题仪表盘图表',
    description: 'Multi-chart dashboard with dark background theme, vibrant neon-like accents.',
    descriptionZh: '深色背景多图表仪表盘，配有鲜亮霓虹色调点缀。',
    imagePath: '/gallery/dark-dashboard.svg',
    thumbnailPath: '/gallery/dark-dashboard.svg',
    source: { type: 'website', name: 'Apache ECharts Dark Theme' },
    chartTypes: ['line', 'bar'],
    journalStyles: ['Custom'],
    colorTones: ['vibrant'],
    colorPalette: ['#00DDFF', '#37A2DA', '#67E0E3', '#FFDB5C', '#FF9F7F'],
    createdAt: Date.now(),
  },
  {
    id: 'g-020',
    title: 'Pastel Multi-series Area',
    titleZh: '柔和色彩多系列面积图',
    description: 'Overlapping area chart with semi-transparent pastel fills for multiple time series.',
    descriptionZh: '半透明柔和配色的多时序堆叠面积图。',
    imagePath: '/gallery/pastel-area.svg',
    thumbnailPath: '/gallery/pastel-area.svg',
    source: { type: 'paper', name: 'PNAS 2024' },
    chartTypes: ['area'],
    journalStyles: ['PNAS'],
    colorTones: ['muted'],
    colorPalette: ['#AEC7E8', '#FFBB78', '#98DF8A', '#FF9896', '#C5B0D5'],
    createdAt: Date.now(),
  },
  // ── Supplemental figures (g-021 ~ g-030) ──
  {
    id: 'g-021',
    title: 'Volcano Plot — Differential Expression',
    titleZh: '火山图 — 差异表达分析',
    description: 'Three-color volcano plot for RNA-seq differential expression, with gene labels on top hits.',
    descriptionZh: '三色火山图用于RNA-seq差异表达分析，顶部命中基因标注。',
    imagePath: '/gallery/volcano-plot.svg',
    thumbnailPath: '/gallery/volcano-plot.svg',
    source: { type: 'paper', name: 'Nature Methods 2024' },
    chartTypes: ['volcano'],
    journalStyles: ['Nature'],
    colorTones: ['vibrant'],
    colorPalette: ['#E64B35', '#3C5488', '#B8B8B8'],
    createdAt: Date.now(),
  },
  {
    id: 'g-022',
    title: 'UMAP Cluster Visualization',
    titleZh: 'UMAP 聚类可视化',
    description: 'Single-cell RNA-seq style UMAP with 8 distinct clusters, commonly seen in Cell and Nature papers.',
    descriptionZh: '单细胞RNA-seq风格UMAP图，8个不同聚类，常见于Cell和Nature论文。',
    imagePath: '/gallery/umap-clusters.svg',
    thumbnailPath: '/gallery/umap-clusters.svg',
    source: { type: 'paper', name: 'Cell 2024' },
    chartTypes: ['scatter'],
    journalStyles: ['Cell'],
    colorTones: ['vibrant'],
    colorPalette: ['#E64B35', '#4DBBD5', '#00A087', '#3C5488', '#F39B7F', '#8491B4', '#91D1C2', '#DC9157'],
    createdAt: Date.now(),
  },
  {
    id: 'g-023',
    title: 'Ridge Plot — Distribution Comparison',
    titleZh: '山脊图 — 分布对比',
    description: 'Overlapping density ridges showing distribution shifts across 8 samples, Nature-style muted palette.',
    descriptionZh: '重叠密度山脊图展示8个样本的分布偏移，Nature风格柔和配色。',
    imagePath: '/gallery/ridge-plot.svg',
    thumbnailPath: '/gallery/ridge-plot.svg',
    source: { type: 'paper', name: 'Nature Communications 2024' },
    chartTypes: ['ridge'],
    journalStyles: ['Nature'],
    colorTones: ['muted'],
    colorPalette: ['#4E79A7', '#F28E2B', '#E15759', '#76B7B2', '#59A14F', '#EDC948', '#B07AA1', '#FF9DA7'],
    createdAt: Date.now(),
  },
  {
    id: 'g-024',
    title: 'Beeswarm Plot with Mean Bars',
    titleZh: '蜂群图（含均值线）',
    description: 'Swarm/beeswarm plot showing individual data points with mean bars for 5 treatment groups.',
    descriptionZh: '蜂群图展示5个处理组的个体数据点，附均值横线标注。',
    imagePath: '/gallery/swarm-plot.svg',
    thumbnailPath: '/gallery/swarm-plot.svg',
    source: { type: 'paper', name: 'PNAS 2024' },
    chartTypes: ['scatter'],
    journalStyles: ['PNAS'],
    colorTones: ['vibrant'],
    colorPalette: ['#E64B35', '#4DBBD5', '#00A087', '#3C5488', '#F39B7F'],
    createdAt: Date.now(),
  },
  {
    id: 'g-025',
    title: 'Waterfall Chart — Financial Flow',
    titleZh: '瀑布图 — 财务流向',
    description: 'Waterfall chart showing cumulative positive/negative changes with connector lines.',
    descriptionZh: '瀑布图展示正负累计变化，带连接线。',
    imagePath: '/gallery/waterfall-chart.svg',
    thumbnailPath: '/gallery/waterfall-chart.svg',
    source: { type: 'website', name: 'Matplotlib Gallery', url: 'https://matplotlib.org/stable/gallery/' },
    chartTypes: ['waterfall'],
    journalStyles: ['Custom'],
    colorTones: ['cool'],
    colorPalette: ['#3C5488', '#00A087', '#E64B35'],
    createdAt: Date.now(),
  },
  {
    id: 'g-026',
    title: 'Bubble Chart — Publication Metrics',
    titleZh: '气泡图 — 出版指标',
    description: 'Bubble scatter plot with size encoding for publication impact metrics across disciplines.',
    descriptionZh: '气泡散点图，用气泡大小编码各学科的出版影响指标。',
    imagePath: '/gallery/bubble-chart.svg',
    thumbnailPath: '/gallery/bubble-chart.svg',
    source: { type: 'paper', name: 'Science 2024' },
    chartTypes: ['bubble'],
    journalStyles: ['Science'],
    colorTones: ['cool'],
    colorPalette: ['#3366CC', '#DC3912', '#FF9900', '#109618', '#990099'],
    createdAt: Date.now(),
  },
  {
    id: 'g-027',
    title: 'Paired Comparison — Before vs After',
    titleZh: '配对对比图 — 处理前后',
    description: 'Paired dot plot with connecting lines showing before/after treatment changes.',
    descriptionZh: '配对点图带连接线，展示治疗前后变化。',
    imagePath: '/gallery/paired-dot-plot.svg',
    thumbnailPath: '/gallery/paired-dot-plot.svg',
    source: { type: 'paper', name: 'Lancet 2024' },
    chartTypes: ['scatter'],
    journalStyles: ['Lancet'],
    colorTones: ['warm'],
    colorPalette: ['#AD002A', '#00468B'],
    createdAt: Date.now(),
  },
  {
    id: 'g-028',
    title: 'Multi-panel Figure Layout',
    titleZh: '多面板组合图',
    description: 'Publication-style multi-panel figure with A/B/C/D labels combining line, bar, heatmap and scatter.',
    descriptionZh: '出版风格多面板组合图，A/B/C/D标签，融合折线、柱状、热力和散点图。',
    imagePath: '/gallery/multi-panel.svg',
    thumbnailPath: '/gallery/multi-panel.svg',
    source: { type: 'paper', name: 'Nature 2024' },
    chartTypes: ['line', 'bar', 'heatmap', 'scatter'],
    journalStyles: ['Nature'],
    colorTones: ['muted'],
    colorPalette: ['#4E79A7', '#F28E2B', '#E15759', '#76B7B2'],
    createdAt: Date.now(),
  },
  {
    id: 'g-029',
    title: 'Correlation Matrix with Significance',
    titleZh: '带显著性标记的相关矩阵',
    description: 'Lower-triangle correlation heatmap with Pearson r values and significance stars.',
    descriptionZh: '下三角相关矩阵热力图，标注Pearson r值和显著性星号。',
    imagePath: '/gallery/correlation-significance.svg',
    thumbnailPath: '/gallery/correlation-significance.svg',
    source: { type: 'paper', name: 'Science Advances 2024' },
    chartTypes: ['heatmap'],
    journalStyles: ['Science'],
    colorTones: ['cool'],
    colorPalette: ['#3366CC', '#FFFFFF', '#DC3912'],
    createdAt: Date.now(),
  },
  {
    id: 'g-030',
    title: '100% Stacked Bar — Component Breakdown',
    titleZh: '百分比堆叠柱状图',
    description: 'Horizontal 100% stacked bar chart showing percentage breakdown across models.',
    descriptionZh: '水平百分比堆叠柱状图，展示各模型的成分占比。',
    imagePath: '/gallery/stacked-percentage.svg',
    thumbnailPath: '/gallery/stacked-percentage.svg',
    source: { type: 'paper', name: 'IEEE TPAMI 2024' },
    chartTypes: ['bar'],
    journalStyles: ['IEEE'],
    colorTones: ['neutral'],
    colorPalette: ['#0072B2', '#D55E00', '#009E73', '#CC79A7', '#F0E442'],
    createdAt: Date.now(),
  },
]

/** All available chart types for filtering */
export const allChartTypes = [
  'line', 'bar', 'scatter', 'heatmap', 'box',
  'violin', 'area', 'radar', 'pie', 'sankey',
  'volcano', 'bubble', 'ridge', 'waterfall', 'other',
] as const

/** All available journal styles for filtering */
export const allJournalStyles = [
  'Nature', 'Science', 'IEEE', 'ACS', 'Cell',
  'PNAS', 'Lancet', 'Custom',
] as const

/** All available color tones for filtering */
export const allColorTones = [
  'warm', 'cool', 'neutral', 'vibrant', 'muted', 'monochrome',
] as const
